spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${VIRTUAL_PRIVATE_CLOUD.IP.PUBLIC}:${DATASOURCE.PORT}/mater_db # ?currentSchema=mater
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
  config:
    import: classpath:.env.yml

server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:copied.${VIRTUAL_PRIVATE_CLOUD.DOMAIN}.p12
    key-store-password: ${SSL.PASSWORD}
    key-store-type: PKCS12
    key-alias: ${VIRTUAL_PRIVATE_CLOUD.DOMAIN}

telegram:
  bot:
    name: Mater
    token: ${TELEGRAM.BOT.TOKEN}
    command:
      start:
        description: Начать выбирать машину
      cars_menu:
        description: Главное меню с машинами
      notifications_menu:
        description: Меню уведомлений об изменениях
      contact_seller:
        description: Связаться с продавцом
      contact_developer:
        description: Связаться с разработчиком бота