spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mater_db?currentSchema=mater
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    locations: classpath:db/migration/default,classpath:db/migration/dev

server:
  ssl:
    enabled: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_DEV_TOKEN}

selectel:
  s3:
    bucket-properties:
      name: mater-bucket-dev
      domain: ${SELECTEL_BUCKET_DEV_DOMAIN}