spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mater_db?currentSchema=mater
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

server:
  ssl:
    enabled: false