spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${VIRTUAL_PRIVATE_CLOUD_PUBLIC_IP}:${DATASOURCE_PORT}/mater_db # ?currentSchema=mater
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
  config:
    import: classpath:.env.properties

server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:copied.${VIRTUAL_PRIVATE_CLOUD_DOMAIN}.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${VIRTUAL_PRIVATE_CLOUD_DOMAIN}

telegram:
  bot:
    name: Mater
    token: ${TELEGRAM_BOT_TOKEN}
    command:
      start:
        description: Начать выбирать машину
      cars_menu:
        description: Главное меню с машинами
      notifications_menu:
        description: Меню уведомлений об изменениях
      contact_seller:
        description: Связаться с продавцом
      contact_developer:
        description: Связаться с разработчиком бота