spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mater_db?currentSchema=mater
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    locations: classpath:db/migration/dev
  mail:
    test-connection: false

server:
  port: 8081
  ssl:
    enabled: false

telegram:
  bot:
    menu:
      button:
        url: https://icy-trees-yell.loca.lt/support