spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mater_db?currentSchema=mater
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration/default,classpath:db/migration/dev
  mail:
    test-connection: false

server:
  ssl:
    enabled: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_DEV_TOKEN}
#    menu:
#      button:
#        url: https://7ecb-85-143-112-77.ngrok-free.app

selectel:
  s3:
    bucket-properties:
      name: mater-bucket-dev
      domain: ${SELECTEL_BUCKET_DEV_DOMAIN}

#cron:
#  config:
#    clean-orphan-objects:
#      expression: '*/59 * * * * *'
