spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${VIRTUAL_PRIVATE_CLOUD_PUBLIC_IP}:${DATASOURCE_PORT}/mater_db?currentSchema=mater
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    pagination:
      page-size: 3
  flyway:
    enabled: true
    locations: classpath:db/migration/default
  config:
    import: classpath:.env.properties
  mail:
    host: smtp.${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender:
      email: ${MAIL_USERNAME}@${MAIL_HOST}
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500GB
  mvc:
    async:
      request-timeout: 10m


server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:copied.${VIRTUAL_PRIVATE_CLOUD_DOMAIN}.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${VIRTUAL_PRIVATE_CLOUD_DOMAIN}

telegram:
  bot:
    name: Mater
    token: ${TELEGRAM_BOT_TOKEN}
    menu:
      type: button
      command:
        start:
          description: Начать
      button:
        title: Открыть приложение
        url: https://oneune.duckdns.org

selectel:
  s3:
    credentials:
      access-key: ${SELECTEL_S3_ACCESS_KEY}
      secret-key: ${SELECTEL_S3_SECRET_KEY}
      url: https://s3.storage.selcloud.ru
      region: ru-1
    bucket-properties:
      name: mater-bucket
      domain: ${SELECTEL_BUCKET_DOMAIN}
    object-properties:
      url-expiration: 1d

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always

cron:
  config:
    clean-orphan-objects:
      name: clean-orphan-selectel-objects
      expression: '* * 4 * * *'
