spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DATASOURCE.HOST}:${DATASOURCE.PORT}/mater_db?currentSchema=mater
#    username: ${DATASOURCE.USERNAME}
#    password: ${DATASOURCE.PASSWORD}
#  jpa:
#    hibernate.ddl-auto: none
#    show-sql: true
#  flyway:
#    enabled: true
  config:
    import: classpath:.env.yml

server:
  port: ${SERVICE.PORT}
  ssl:
    enabled: true
    key-store: classpath:copied.${SERVICE.DOMAIN}.p12
    key-store-password: ${SSL.PASSWORD}
    key-store-type: PKCS12
    key-alias: ${SERVICE.DOMAIN}

telegram:
  bot:
    name: Mater
    token: ${TELEGRAM.BOT.TOKEN}
    command:
      start:
        description: Начать