spring:
  config:
    import:
      - optional:file:.env.yml

telegram:
  bot:
    name: ${TELEGRAM.BOT.NAME}
    token: ${TELEGRAM.BOT.TOKEN}
    command:
      start:
        description: Начать

server:
  port: 8080
